### ISSUE TITLE
Print format bug

### ISSUE THREAD

**Issue by mtnredhed** [mbridak/fdserver#3]
in  `_main_.py` lines 677 and 678.

You print out the bool value for BATTERYPOWER  but don't print out the label.  This causes the BATTERYPOWER value to be printed next to the section when in stead it should have it's own label under section as either  AltPower or BatteryPower

**Comment by mbridak** [comment]
Why did I do that...

**Comment by mbridak** [comment]
Okay. I went with the assumption that I was trying to remove useless info from the screen.
Since there are too many items to fit on the screen. Battery power vs Alt-Power etc.
So I ended up removing the Bool from the screen.

**Comment by mtnredhed** [comment]
Thank you sir. 
Currently testing the "beta" of not1mm.  I need to get them to fix the pipx build of PyQt6 on Raspberry Pi.   Works fine on Linux Mint on intel but I'd like something easier to run off of 12v with just a dc to dc  12>5vdc power supply.  Oddly, I can "sudo apt install python3-pyqt6" which will build correctly but outside the sandbox.

**Comment by mbridak** [comment]
It maybe that you'd have to install some pyqt6 dev files to allow pip to
build it on the fly.
